# Site settings
title: lionel's resume
description: lionel's resume
favicon: /iCard-Resume/assets/img/avatar.JPG
baseurl: http://lionel0806.github.io/resume
url: http://lionel0806.github.io/resume
rss_url: /iCard-Resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: 李贤
  title: c/c++ 工程师
  address: 北京
  email: lixiansir@gmail.com
  link: http://lionel0806.github.io
  weibo: http://weibo.com/lionel0806
  github: lionel0806
  linkedin: lionel0806
  gavatar: /iCard-Resume/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Goosat
      location: 广东珠海
      title: Linux C 工程师
      started: 2012
      duration: (2012 - 2014)
      description: 嵌入式Linux平台上卫星视频直播应用程序的开发，维护工作，涉及MPEG-4/H264 解码，Linux C的开发，移植以及调试。 
    - work2:
      company: 天脉聚源（Tvmining）
      location: 北京
      title: iOS Developer
      started: 2015
      duration: (2015 - ~)
      description: 视频直播相关iOS应用的开发，迭代，维护工作。
  educationHistory:
    - education1:
      organization: 兰州大学
      degree: 本科
      major: 信息与计算科学
      started: 2008
      duration: (2008 - 2012)
      description: 
  languages:
    - language1:
      name: English
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Linux
      percentage: 60%
    - skill2:
      name: C
      percentage: 80%
    - skill3:
      name: Objective-c
      percentage: 80%
    - skill4:
      name: Cocoa
      percentage: 40%
    - skill5:
      name: Git
      percentage: 80%
